import dotenv from 'dotenv';

dotenv.config();

const env = process.env;

export const envConfig = {
    ENVIRONMENT: env.ENVIRONMENT || '',
    SERVER_URL: env.SERVER_URL || '',
    DOMAIN_URL: env.DOMAIN_URL || '',
    KONG_URL: env.KONG_URL || '',
    DEVELOPMENT_REACT_APP_URL: env.DEVELOPMENT_REACT_APP_URL || '',
    SUNBIRD_YUGABYTE_HOST: env.SUNBIRD_YUGABYTE_HOST || '',
    FORMS_DB_NAME: env.FORMS_DB_NAME || '',
    CONTENT_REVIEW_COMMENT_DB_NAME: env.CONTENT_REVIEW_COMMENT_DB_NAME || '',
    KONG_ANONYMOUS_FALLBACK_TOKEN: env.KONG_ANONYMOUS_FALLBACK_TOKEN || '',
    KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN: env.KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN || '',
    SUNBIRD_SESSION_SECRET: env.SUNBIRD_SESSION_SECRET || 'default_secret',
    KONG_LOGGEDIN_FALLBACK_TOKEN: env.KONG_LOGGEDIN_FALLBACK_TOKEN || '',
    KONG_LOGGEDIN_DEVICE_REGISTER_TOKEN: env.KONG_LOGGEDIN_DEVICE_REGISTER_TOKEN || '',
    PORTAL_REALM: env.PORTAL_REALM || '',
    PORTAL_AUTH_SERVER_CLIENT: env.PORTAL_AUTH_SERVER_CLIENT || '',
    GOOGLE_OAUTH_CLIENT_ID: env.GOOGLE_OAUTH_CLIENT_ID || '',
    GOOGLE_OAUTH_CLIENT_SECRET: env.GOOGLE_OAUTH_CLIENT_SECRET || '',
    KEYCLOAK_GOOGLE_CLIENT_ID: env.KEYCLOAK_GOOGLE_CLIENT_ID || '',
    KEYCLOAK_GOOGLE_CLIENT_SECRET: env.KEYCLOAK_GOOGLE_CLIENT_SECRET || '',
    KEYCLOAK_ANDROID_CLIENT_ID: env.KEYCLOAK_ANDROID_CLIENT_ID || '',
    KEYCLOAK_ANDROID_CLIENT_SECRET: env.KEYCLOAK_ANDROID_CLIENT_SECRET || '',
    KEYCLOAK_GOOGLE_ANDROID_CLIENT_ID: env.KEYCLOAK_GOOGLE_ANDROID_CLIENT_ID || '',
    KEYCLOAK_GOOGLE_ANDROID_CLIENT_SECRET: env.KEYCLOAK_GOOGLE_ANDROID_CLIENT_SECRET || '',
    GOOGLE_OAUTH_CLIENT_ID_IOS: env.GOOGLE_OAUTH_CLIENT_ID_IOS || '',
    OIDC_ISSUER_URL: env.OIDC_ISSUER_URL || '',

    // OPTIONAL ENVIRONMENT VARIABLES
    PORT: parseInt(env.PORT || '3000'),
    SUNBIRD_PORTAL_LOG_LEVEL: env.SUNBIRD_PORTAL_LOG_LEVEL || 'debug',
    SUNBIRD_ANONYMOUS_SESSION_TTL: parseInt(env.SUNBIRD_ANONYMOUS_SESSION_TTL || "60000"),
    SUNBIRD_YUGABYTE_PORT: parseInt(env.SUNBIRD_YUGABYTE_PORT || '5433'),
    SUNBIRD_YUGABYTE_YCQL_PORT: parseInt(env.SUNBIRD_YUGABYTE_YCQL_PORT || '9042'),
    SUNBIRD_YUGABYTE_DATABASE: env.SUNBIRD_YUGABYTE_DATABASE || 'portal',
    SUNBIRD_YUGABYTE_USER: env.SUNBIRD_YUGABYTE_USER || '',
    SUNBIRD_YUGABYTE_PASSWORD: env.SUNBIRD_YUGABYTE_PASSWORD || '',
    SUNBIRD_PORTAL_SESSION_STORE: env.SUNBIRD_PORTAL_SESSION_STORE || 'in-memory',
    GOOGLE_RECAPTCHA_VERIFY_URL: env.GOOGLE_RECAPTCHA_VERIFY_URL || 'https://www.google.com/recaptcha/api/siteverify',
    GOOGLE_RECAPTCHA_SECRET: env.GOOGLE_RECAPTCHA_SECRET || '',
    APPID: (env.ENVIRONMENT || 'local') + '.' + (env.SUNBIRD_PORTAL_INSTANCE || 'sunbird') + '.portal',
    LEARN_BASE_URL: env.LEARN_BASE_URL || 'http://userorg-service:9000',
    KNOWLG_MW_BASE_URL: env.KNOWLG_MW_BASE_URL || 'http://knowledge-mw-service:5000',
};